export enum ROOT_ROUTES {
  AUTH_NAVIGATION = 'AUTH_NAVIGATION',
  APP_NAVIGATION = 'APP_NAVIGATION',
  SIGN_UP_SURVEY = 'SIGN_UP_SURVEY',
  PROFILE_PREFERENCE = 'PROFILE_PREFERENCE',
  MEDIA = '[APP] MEDIA',
  COMMENT = '[APP] COMMENT',
  CHAT = '[APP] CHAT',
}

export enum AUTH_NAVIGATION {
  LOGIN = '[AUTH] LOGIN',
  REGISTER = '[AUTH] REGISTER',
  FORGOT_PASSWORD = '[AUTH] FORGOT_PASSWORD',
  CHANGE_PASSWORD = '[AUTH] CHANGE_PASSWORD',
  SURVEY_FAV = '[AUTH] SURVEY_FAV',
  USER_INFORMATION = '[AUTH] USER_INFORMATION',
  CHOOSE_AVATAR = '[AUTH] CHOOSE_AVATAR',
}

export enum APP_NAVIGATION {
  HOME = '[APP] HOME',
  SEARCH = '[APP] SEARCH',
  CREATE = '[APP] CREATE',
  NOTIFICATION = '[APP] NOTIFICATION',
  PROFILE = '[APP] PROFILE',

  MARKET = '[APP] MARKET',
  SPORT = '[APP] SPORT',
}

export enum HOME_NAVIGATION {
  NEW_FEED = '[HOME] NEW_FEED',
  DRAFTHOME = '[HOME] DRAFTHOME',
  SCHEDULEDHOME = '[HOME] SCHEDULEDHOME',
  DISCOVERY = '[HOME] DISCOVERY',
  RESCHEDULEHOME = 'RESCHEDULEHOME',
  EDIT_STUMP = 'EDIT_STUMP',
}
