export enum ROOT_ROUTES {
  AUTH_NAVIGATION = 'AUTH_NAVIGATION',
  APP_NAVIGATION = 'APP_NAVIGATION',
  SIGN_UP_SURVEY = 'SIGN_UP_SURVEY',
  PROFILE_PREFERENCE = 'PROFILE_PREFERENCE',
  MEDIA = '[APP] MEDIA',
  COMMENT = '[APP] COMMENT',
  CHAT = '[APP] CHAT',
}

export enum AUTH_NAVIGATION {
  LOGIN = '[AUTH] LOGIN',
  REGISTER = '[AUTH] REGISTER',
  FORGOT_PASSWORD = '[AUTH] FORGOT_PASSWORD',
  CHANGE_PASSWORD = '[AUTH] CHANGE_PASSWORD',
  SURVEY_FAV = '[AUTH] SURVEY_FAV',
  USER_INFORMATION = '[AUTH] USER_INFORMATION',
  CHOOSE_AVATAR = '[AUTH] CHOOSE_AVATAR',
}

export enum APP_NAVIGATION {
  HOME = '[APP] HOME',
  PRODUCT = '[APP] PRODUCT',
  CART = '[APP] CART',
  PROFILE = '[APP] PROFILE',
}

export enum HOME_NAVIGATION {
  NEW_FEED = '[HOME] NEW_FEED',
  DRAFTHOME = '[HOME] DRAFTHOME',
  SCHEDULEDHOME = '[HOME] SCHEDULEDHOME',
  DISCOVERY = '[HOME] DISCOVERY',
  RESCHEDULEHOME = 'RESCHEDULEHOME',
  EDIT_STUMP = 'EDIT_STUMP',
}

export enum PRODUCT_NAVIGATION {
  ALLPRODUCT = '[PRODUCT] ALL_PRODUCT',
  DETAILPRODUCT = '[PRODUCT] DETAIL_PRODUCT',
  SIZEPRODUCT = '[PRODUCT] SIZE_PRODUCT',
}

export enum CART_NAVIGATION {
  ITEMSCART = '[CART] ITEMS_CART',
  PAYMENTCART = '[CART] PAYMENT_CART',
}
