export const ApiRoutes = {
  authentication: {
    login: '/user/login',
    forgotPassword: '/user/forgotPassword',
    changePassword: '/user/changePassword',
    register: '/user/register',
    logout: '/users/logout',
    loginApple: 'user/loginWithApple',
    loginFacebook: 'user/loginWithFacebook',
    loginLinkedin: 'user/loginWithLinkedIn',
    loginTwitter: 'user/loginWithTwitter',
    twitterRequestToken: 'user/twitterRequestToken',
    twitterVerifyCredentials: 'user/twitterVerifyCredentials',
    addDevice: 'user/addDevice',
    removeDevice: 'user/removeDevice',
  },
  user: {
    findUser: 'stump/findUser',
    checkBlockStatus: 'stump/checkBlockStatus',
    validateName: 'user/validateName',
    searchAllUser: 'user/searchAllUser',
    getAllFriends: 'stump/getAllFriends',
    allNewNotis: 'user/allNewNotis',
    getSports: 'survey/sport',
    getMarkets: 'survey/market',
    getLeagues: 'survey/league',
    getTeams: 'survey/team',
    fetchUser: 'stump/getProfileUser',
    updateUserSurvey: 'user/updateUserSurvey',
    findByDisplayName: 'user/findByName',
    userSurveyInfo: 'user/userSurveyInfo',
    blockUser: 'stump/blockUser',
    verifyOtp: 'user/verifyOtp',
    validatePhone: 'user/validatePhone',
    sendOtp: 'user/sendOtp',
    updatePhone: 'user/updatePhone',
    getListFollower: 'stump/getListFollower',
    getListFollowing: 'stump/getListFollowing',
    editProfile: 'user/editProfile',
    clearBadge: 'user/clearBadge',
  },
  stump: {
    getListStump: 'stump/getListStump',
    getListStumpCreated: 'stump/listStumpCreated',
    getListStumpLike: 'stump/listStumpLike',
    getListStumpJoined: 'stump/listStumpJoined',
    getListStumpShared: 'stump/getListStumpShared',
    counterPlayAudio: 'stump/counterPlayAudio',
    getDetailStump: 'stump/getDetailStump',
    reactionStump: 'stump/reactionStump',
    shareStump: 'stump/shareStump',
    followUser: 'stump/followUser',
    unShareStump: 'stump/unShareStump',
    addStump: 'stump/addStump',
    removeStump: 'stump/removeStump',
    editStump: 'stump/editStump',
    uploadAudio: 'stump/uploadAudio',
    reportStump: 'stump/reportStump',
    getRamdomAds: 'ads/random',
  },
  conversation: {
    addConversation: 'stump/addConversation',
    removeConversation: 'stump/removeConversation',
    editConversation: 'stump/editConversation',
    getDetailConversation: 'stump/getDetailConversation',
    getConversationNumber: 'stump/getConversationNumber',
    getConversationFinished: 'stump/getConversationFinished',
    getConversationScheduled: 'stump/getConversationScheduled',
    getListAcceptedConv: 'stump/getListAcceptedConv',
    declineAcceptedConversation: 'stump/decline',
    updateDraft: 'stump/updateDraft',
    findInviteCode: 'stump/findInviteCode',
  },
  provider: {
    presignedUrl: 'user/presignedUrl',
  },
  search: {
    searchByName: 'user/searchAllUser',
    getDefaultSearch: 'stump/getListHastag',
    searchStump: 'stump/searchStump',
    getNumberStump: 'feed/getNumberOfStump',
    getListStumpBySurveyId: 'feed/getListStumpBySurveyId',
  },
  comment: {
    getComment: 'message/comment',
    sendReply: 'message/comment',
    likeReply: 'message/comment-reaction',
    mention: 'message/mention',
  },
  agora: {
    getAccessToken: 'record/getAccessToken',
  },
  notification: {
    listNotification: 'stump/listNotification',
    hideNotification: 'stump/hideNotification',
    joinNowFromNotification: 'stump/joinNowFromNotification',
    seeNotification: 'stump/seeNotification',
  },
  chat: {
    message: 'message',
    video: 'message/video',
    getAllRoomChat: 'message/room',
    archiveRoom: 'message/archive-room',
    reaction: 'message/reaction',
  },
  trending: {
    getEvent: 'feed/posts',
    getMatch: 'feed/matches',
    getListStumpByPost: 'feed/stumpByPostId',
    getListStumpByMatch: 'feed/stumpByMatchId',
  },
};
