import { Colors } from '@/theme/colors';
import { StyleSheet } from 'react-native';
import { scale } from 'react-native-size-scaling';

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    // backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'flex-end',
  },
  modalView: {
    backgroundColor: Colors.White,
    borderTopLeftRadius: scale(10),
    borderTopRightRadius: scale(10),
    minHeight: '35%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    height: scale(50),
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: Colors.WhiteSmoke,
  },
  headerText: {
    textAlign: 'center',
    fontSize: scale(22),
    lineHeight: scale(30),
    fontFamily: 'Lexend-Bold',
    color: Colors.blackOriginal,
  },
  body: {
    paddingHorizontal: scale(20),
    paddingBottom: scale(20),
    width: '100%',
    height: '100%',
    flex: 1,
  },
  cancelButtonView: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.Dark_Gray2,
    height: scale(40),
    borderRadius: scale(20),
  },
  cancelButtonText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: scale(15),
  },
  iconView: {
    paddingVertical: scale(6),
    flexDirection: 'row',
    justifyContent: 'center',
    borderBottomWidth: scale(1),
    borderBottomColor: Colors.Graylish_blue,
  },
  iconViewDisable: {
    backgroundColor: 'rgba(192, 192, 192, 1)',
  },
  stumpIconView: {
    padding: scale(2),
    borderRadius: scale(10),
    borderWidth: 1,
    borderColor: Colors.Gray,
    width: scale(48),
    height: scale(48),
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialText: {
    textAlign: 'center',
    fontSize: scale(14),
    marginTop: scale(5),
    marginLeft: scale(10),
    fontFamily: 'Lexend-Bold',
  },
  sign: {
    backgroundColor: Colors.Dark_Gray2,
    height: scale(8),
    width: scale(70),
    borderRadius: scale(5),
    marginTop: scale(5),
  },
  viewMore: {
    backgroundColor: Colors.White,
    padding: scale(2),
    borderRadius: scale(6),
    width: scale(45),
    height: scale(45),
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: Colors.Dark_Gray2,
    borderWidth: scale(1),
  },
  viewRestump: {
    backgroundColor: Colors.Background2,
    padding: scale(2),
    borderRadius: scale(6),
    width: scale(45),
    height: scale(45),
  },
});
